<?php
/**
 * TO-DO  File
 */

// API
// TODO WEB SCRAPER

//  BACK OFFICE
// TODO KARDEX INTEGRATION
// TODO WARRANTY REPLACE ITEM , PAY DIFFERENCE , CASHBACK
// TODO CLAIMS END CLAIMS
// TODO INVOICE => SHIPPING COST INFINITY
// TODO PROFILE ROLE SETUP BY STORE
// TODO FILTER CONTENT BY ROLE AND PERMISSIONS
// TODO EXPENSES
// DONE SHIFT ATTENDANCE RECORD
// APP
// TODO HOME DASHBOARD COUNTER FILTER DATES
// TODO CHECK INVOICE 35 BAD TAX CONFIGURATION
// TODO MINIMUM PRICE ONLY ON EXISTENCE

// * REPORTS
// TODO REPORTS => INVENTORY REPORT = > FILTER BY FEATURE
// TODO REPORTS => ESTADO DE RESULTADOS
// TODO EXPENSES REPORT
// DONE ATTENDANCE REPORT